### ISSUE TITLE
Informational: many countries are standardizing OpenAPI 3

### ISSUE THREAD

**Issue by ioggstream** [ongov/API-Guidelines#9]
## Informational

If you want consistent API specs b/w different agencies, I'd explicitly ask for OAS3 or above in
https://github.com/ongov/API-Guidelines/blob/master/API-Guidelines.md#use-openapi-for-restful-apis

Otherwise you will have to support two different parsers and couldn't get all the new OAS3 features (eg. 3.1 should deliver mutualTLS, summary field and xmlschema support).

**Comment by nickgee** [comment]
See https://github.com/ongov/API-Guidelines/pull/13
